add_newline = true

[battery]
disabled = true

[character]
format = "$symbol â® "
success_symbol = "[á“šá˜á—¢](green)"
error_symbol = "[á“šá˜á—¢](red)"
vicmd_symbol = "[á—¢á˜á“—](blue)"

[git_branch]
style = "green"
symbol = ""

[git_status]
conflicted = "ğŸ³"
ahead = "ï„½ "
behind = "ïƒ‚ "
diverged = "ïƒ¹ "
untracked = "ï„¨"
stashed = "ï†‡ "
modified = "ï„ "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ï‹‚ "
deleted = "ğŸ—‘"

[golang]
symbol = "î˜§ "

[python]
symbol = "î˜† "

[ruby]
symbol = "î‘ "

