add_newline = true

[battery]
disabled = true

[character]
symbol = " `ï½¥Ï‰ ï½¥Â´  "
vicmd_symbol = " Â´ï½¥Ï‰ ï½¥`  "
style_success = "white bg:#3464b3"
style_failure = "white bg:#d1544b"

[git_branch]
style = "green"
symbol = ""

[git_status]
conflicted = "ğŸ³"
ahead = "ï„½ "
behind = "ïƒ‚ "
diverged = "ïƒ¹ "
untracked = "ï„¨"
stashed = "ï†‡ "
modified = "ï„ "
staged.value = "++"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
renamed = "ï‹‚ "
deleted = "ğŸ—‘"

[golang]
symbol = "î˜§ "

[python]
symbol = "î˜† "

[ruby]
symbol = "î‘ "

